/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1MyUser200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1MyUser200Response{}

// V1MyUser200Response struct for V1MyUser200Response
type V1MyUser200Response struct {
	User                 UserModel `json:"user"`
	AdditionalProperties map[string]interface{}
}

type _V1MyUser200Response V1MyUser200Response

// NewV1MyUser200Response instantiates a new V1MyUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1MyUser200Response(user UserModel) *V1MyUser200Response {
	this := V1MyUser200Response{}
	this.User = user
	return &this
}

// NewV1MyUser200ResponseWithDefaults instantiates a new V1MyUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1MyUser200ResponseWithDefaults() *V1MyUser200Response {
	this := V1MyUser200Response{}
	return &this
}

// GetUser returns the User field value
func (o *V1MyUser200Response) GetUser() UserModel {
	if o == nil {
		var ret UserModel
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *V1MyUser200Response) GetUserOk() (*UserModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *V1MyUser200Response) SetUser(v UserModel) {
	o.User = v
}

func (o V1MyUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1MyUser200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1MyUser200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1MyUser200Response := _V1MyUser200Response{}

	err = json.Unmarshal(data, &varV1MyUser200Response)

	if err != nil {
		return err
	}

	*o = V1MyUser200Response(varV1MyUser200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1MyUser200Response struct {
	value *V1MyUser200Response
	isSet bool
}

func (v NullableV1MyUser200Response) Get() *V1MyUser200Response {
	return v.value
}

func (v *NullableV1MyUser200Response) Set(val *V1MyUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1MyUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1MyUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1MyUser200Response(val *V1MyUser200Response) *NullableV1MyUser200Response {
	return &NullableV1MyUser200Response{value: val, isSet: true}
}

func (v NullableV1MyUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1MyUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
