/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the InvitationModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvitationModel{}

// InvitationModel struct for InvitationModel
type InvitationModel struct {
	Id                   string    `json:"id"`
	Email                string    `json:"email"`
	Status               string    `json:"status"`
	Role                 string    `json:"role"`
	SentAt               time.Time `json:"sent_at"`
	AdditionalProperties map[string]interface{}
}

type _InvitationModel InvitationModel

// NewInvitationModel instantiates a new InvitationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationModel(id string, email string, status string, role string, sentAt time.Time) *InvitationModel {
	this := InvitationModel{}
	this.Id = id
	this.Email = email
	this.Status = status
	this.Role = role
	this.SentAt = sentAt
	return &this
}

// NewInvitationModelWithDefaults instantiates a new InvitationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationModelWithDefaults() *InvitationModel {
	this := InvitationModel{}
	return &this
}

// GetId returns the Id field value
func (o *InvitationModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InvitationModel) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *InvitationModel) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InvitationModel) SetEmail(v string) {
	o.Email = v
}

// GetStatus returns the Status field value
func (o *InvitationModel) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InvitationModel) SetStatus(v string) {
	o.Status = v
}

// GetRole returns the Role field value
func (o *InvitationModel) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *InvitationModel) SetRole(v string) {
	o.Role = v
}

// GetSentAt returns the SentAt field value
func (o *InvitationModel) GetSentAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetSentAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SentAt, true
}

// SetSentAt sets field value
func (o *InvitationModel) SetSentAt(v time.Time) {
	o.SentAt = v
}

func (o InvitationModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvitationModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	toSerialize["status"] = o.Status
	toSerialize["role"] = o.Role
	toSerialize["sent_at"] = o.SentAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvitationModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"status",
		"role",
		"sent_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvitationModel := _InvitationModel{}

	err = json.Unmarshal(data, &varInvitationModel)

	if err != nil {
		return err
	}

	*o = InvitationModel(varInvitationModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "email")
		delete(additionalProperties, "status")
		delete(additionalProperties, "role")
		delete(additionalProperties, "sent_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvitationModel struct {
	value *InvitationModel
	isSet bool
}

func (v NullableInvitationModel) Get() *InvitationModel {
	return v.value
}

func (v *NullableInvitationModel) Set(val *InvitationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationModel(val *InvitationModel) *NullableInvitationModel {
	return &NullableInvitationModel{value: val, isSet: true}
}

func (v NullableInvitationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
