/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1CreateProject201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CreateProject201Response{}

// V1CreateProject201Response struct for V1CreateProject201Response
type V1CreateProject201Response struct {
	Project              ProjectModel `json:"project"`
	AdditionalProperties map[string]interface{}
}

type _V1CreateProject201Response V1CreateProject201Response

// NewV1CreateProject201Response instantiates a new V1CreateProject201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CreateProject201Response(project ProjectModel) *V1CreateProject201Response {
	this := V1CreateProject201Response{}
	this.Project = project
	return &this
}

// NewV1CreateProject201ResponseWithDefaults instantiates a new V1CreateProject201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CreateProject201ResponseWithDefaults() *V1CreateProject201Response {
	this := V1CreateProject201Response{}
	return &this
}

// GetProject returns the Project field value
func (o *V1CreateProject201Response) GetProject() ProjectModel {
	if o == nil {
		var ret ProjectModel
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *V1CreateProject201Response) GetProjectOk() (ProjectModel, bool) {
	if o == nil {
		return ProjectModel{}, false
	}
	return o.Project, true
}

// SetProject sets field value
func (o *V1CreateProject201Response) SetProject(v ProjectModel) {
	o.Project = v
}

func (o V1CreateProject201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CreateProject201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project"] = o.Project

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1CreateProject201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CreateProject201Response := _V1CreateProject201Response{}

	err = json.Unmarshal(data, &varV1CreateProject201Response)

	if err != nil {
		return err
	}

	*o = V1CreateProject201Response(varV1CreateProject201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "project")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1CreateProject201Response struct {
	value *V1CreateProject201Response
	isSet bool
}

func (v NullableV1CreateProject201Response) Get() *V1CreateProject201Response {
	return v.value
}

func (v *NullableV1CreateProject201Response) Set(val *V1CreateProject201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CreateProject201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CreateProject201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CreateProject201Response(val *V1CreateProject201Response) *NullableV1CreateProject201Response {
	return &NullableV1CreateProject201Response{value: val, isSet: true}
}

func (v NullableV1CreateProject201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CreateProject201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
