/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1UpdateChannelRequestSmssInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UpdateChannelRequestSmssInner{}

// V1UpdateChannelRequestSmssInner struct for V1UpdateChannelRequestSmssInner
type V1UpdateChannelRequestSmssInner struct {
	Id                   *string `json:"id,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Phone                string  `json:"phone"`
	AdditionalProperties map[string]interface{}
}

type _V1UpdateChannelRequestSmssInner V1UpdateChannelRequestSmssInner

// NewV1UpdateChannelRequestSmssInner instantiates a new V1UpdateChannelRequestSmssInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UpdateChannelRequestSmssInner(phone string) *V1UpdateChannelRequestSmssInner {
	this := V1UpdateChannelRequestSmssInner{}
	this.Phone = phone
	return &this
}

// NewV1UpdateChannelRequestSmssInnerWithDefaults instantiates a new V1UpdateChannelRequestSmssInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UpdateChannelRequestSmssInnerWithDefaults() *V1UpdateChannelRequestSmssInner {
	this := V1UpdateChannelRequestSmssInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1UpdateChannelRequestSmssInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateChannelRequestSmssInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1UpdateChannelRequestSmssInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V1UpdateChannelRequestSmssInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1UpdateChannelRequestSmssInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateChannelRequestSmssInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1UpdateChannelRequestSmssInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1UpdateChannelRequestSmssInner) SetName(v string) {
	o.Name = &v
}

// GetPhone returns the Phone field value
func (o *V1UpdateChannelRequestSmssInner) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *V1UpdateChannelRequestSmssInner) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *V1UpdateChannelRequestSmssInner) SetPhone(v string) {
	o.Phone = v
}

func (o V1UpdateChannelRequestSmssInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UpdateChannelRequestSmssInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["phone"] = o.Phone

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1UpdateChannelRequestSmssInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1UpdateChannelRequestSmssInner := _V1UpdateChannelRequestSmssInner{}

	err = json.Unmarshal(data, &varV1UpdateChannelRequestSmssInner)

	if err != nil {
		return err
	}

	*o = V1UpdateChannelRequestSmssInner(varV1UpdateChannelRequestSmssInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "phone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1UpdateChannelRequestSmssInner struct {
	value *V1UpdateChannelRequestSmssInner
	isSet bool
}

func (v NullableV1UpdateChannelRequestSmssInner) Get() *V1UpdateChannelRequestSmssInner {
	return v.value
}

func (v *NullableV1UpdateChannelRequestSmssInner) Set(val *V1UpdateChannelRequestSmssInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UpdateChannelRequestSmssInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UpdateChannelRequestSmssInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UpdateChannelRequestSmssInner(val *V1UpdateChannelRequestSmssInner) *NullableV1UpdateChannelRequestSmssInner {
	return &NullableV1UpdateChannelRequestSmssInner{value: val, isSet: true}
}

func (v NullableV1UpdateChannelRequestSmssInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UpdateChannelRequestSmssInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
