/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } } 

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1CreateProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CreateProjectRequest{}

// V1CreateProjectRequest struct for V1CreateProjectRequest
type V1CreateProjectRequest struct {
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _V1CreateProjectRequest V1CreateProjectRequest

// NewV1CreateProjectRequest instantiates a new V1CreateProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CreateProjectRequest(name string) *V1CreateProjectRequest {
	this := V1CreateProjectRequest{}
	this.Name = name
	return &this
}

// NewV1CreateProjectRequestWithDefaults instantiates a new V1CreateProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CreateProjectRequestWithDefaults() *V1CreateProjectRequest {
	this := V1CreateProjectRequest{}
	return &this
}

// GetName returns the Name field value
func (o *V1CreateProjectRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1CreateProjectRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1CreateProjectRequest) SetName(v string) {
	o.Name = v
}

func (o V1CreateProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CreateProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1CreateProjectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CreateProjectRequest := _V1CreateProjectRequest{}

	err = json.Unmarshal(data, &varV1CreateProjectRequest)

	if err != nil {
		return err
	}

	*o = V1CreateProjectRequest(varV1CreateProjectRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1CreateProjectRequest struct {
	value *V1CreateProjectRequest
	isSet bool
}

func (v NullableV1CreateProjectRequest) Get() *V1CreateProjectRequest {
	return v.value
}

func (v *NullableV1CreateProjectRequest) Set(val *V1CreateProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CreateProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CreateProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CreateProjectRequest(val *V1CreateProjectRequest) *NullableV1CreateProjectRequest {
	return &NullableV1CreateProjectRequest{value: val, isSet: true}
}

func (v NullableV1CreateProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CreateProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


