/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1CreateChannelRequestWebhooksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CreateChannelRequestWebhooksInner{}

// V1CreateChannelRequestWebhooksInner struct for V1CreateChannelRequestWebhooksInner
type V1CreateChannelRequestWebhooksInner struct {
	Name                 string `json:"name"`
	Url                  string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _V1CreateChannelRequestWebhooksInner V1CreateChannelRequestWebhooksInner

// NewV1CreateChannelRequestWebhooksInner instantiates a new V1CreateChannelRequestWebhooksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CreateChannelRequestWebhooksInner(name string, url string) *V1CreateChannelRequestWebhooksInner {
	this := V1CreateChannelRequestWebhooksInner{}
	this.Name = name
	this.Url = url
	return &this
}

// NewV1CreateChannelRequestWebhooksInnerWithDefaults instantiates a new V1CreateChannelRequestWebhooksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CreateChannelRequestWebhooksInnerWithDefaults() *V1CreateChannelRequestWebhooksInner {
	this := V1CreateChannelRequestWebhooksInner{}
	return &this
}

// GetName returns the Name field value
func (o *V1CreateChannelRequestWebhooksInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1CreateChannelRequestWebhooksInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1CreateChannelRequestWebhooksInner) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *V1CreateChannelRequestWebhooksInner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *V1CreateChannelRequestWebhooksInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *V1CreateChannelRequestWebhooksInner) SetUrl(v string) {
	o.Url = v
}

func (o V1CreateChannelRequestWebhooksInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CreateChannelRequestWebhooksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1CreateChannelRequestWebhooksInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CreateChannelRequestWebhooksInner := _V1CreateChannelRequestWebhooksInner{}

	err = json.Unmarshal(data, &varV1CreateChannelRequestWebhooksInner)

	if err != nil {
		return err
	}

	*o = V1CreateChannelRequestWebhooksInner(varV1CreateChannelRequestWebhooksInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1CreateChannelRequestWebhooksInner struct {
	value *V1CreateChannelRequestWebhooksInner
	isSet bool
}

func (v NullableV1CreateChannelRequestWebhooksInner) Get() *V1CreateChannelRequestWebhooksInner {
	return v.value
}

func (v *NullableV1CreateChannelRequestWebhooksInner) Set(val *V1CreateChannelRequestWebhooksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CreateChannelRequestWebhooksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CreateChannelRequestWebhooksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CreateChannelRequestWebhooksInner(val *V1CreateChannelRequestWebhooksInner) *NullableV1CreateChannelRequestWebhooksInner {
	return &NullableV1CreateChannelRequestWebhooksInner{value: val, isSet: true}
}

func (v NullableV1CreateChannelRequestWebhooksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CreateChannelRequestWebhooksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
