/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the ChannelSlackModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelSlackModel{}

// ChannelSlackModel struct for ChannelSlackModel
type ChannelSlackModel struct {
	Id                   string `json:"id"`
	IntegrationId        string `json:"integration_id"`
	AdditionalProperties map[string]interface{}
}

type _ChannelSlackModel ChannelSlackModel

// NewChannelSlackModel instantiates a new ChannelSlackModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelSlackModel(id string, integrationId string) *ChannelSlackModel {
	this := ChannelSlackModel{}
	this.Id = id
	this.IntegrationId = integrationId
	return &this
}

// NewChannelSlackModelWithDefaults instantiates a new ChannelSlackModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelSlackModelWithDefaults() *ChannelSlackModel {
	this := ChannelSlackModel{}
	return &this
}

// GetId returns the Id field value
func (o *ChannelSlackModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelSlackModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelSlackModel) SetId(v string) {
	o.Id = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *ChannelSlackModel) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *ChannelSlackModel) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *ChannelSlackModel) SetIntegrationId(v string) {
	o.IntegrationId = v
}

func (o ChannelSlackModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelSlackModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["integration_id"] = o.IntegrationId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChannelSlackModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"integration_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelSlackModel := _ChannelSlackModel{}

	err = json.Unmarshal(data, &varChannelSlackModel)

	if err != nil {
		return err
	}

	*o = ChannelSlackModel(varChannelSlackModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "integration_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChannelSlackModel struct {
	value *ChannelSlackModel
	isSet bool
}

func (v NullableChannelSlackModel) Get() *ChannelSlackModel {
	return v.value
}

func (v *NullableChannelSlackModel) Set(val *ChannelSlackModel) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelSlackModel) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelSlackModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelSlackModel(val *ChannelSlackModel) *NullableChannelSlackModel {
	return &NullableChannelSlackModel{value: val, isSet: true}
}

func (v NullableChannelSlackModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelSlackModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
