/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1UpdateChannelRequestEmailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UpdateChannelRequestEmailsInner{}

// V1UpdateChannelRequestEmailsInner struct for V1UpdateChannelRequestEmailsInner
type V1UpdateChannelRequestEmailsInner struct {
	Id                   *string `json:"id,omitempty"`
	Email                string  `json:"email"`
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1UpdateChannelRequestEmailsInner V1UpdateChannelRequestEmailsInner

// NewV1UpdateChannelRequestEmailsInner instantiates a new V1UpdateChannelRequestEmailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UpdateChannelRequestEmailsInner(email string) *V1UpdateChannelRequestEmailsInner {
	this := V1UpdateChannelRequestEmailsInner{}
	this.Email = email
	return &this
}

// NewV1UpdateChannelRequestEmailsInnerWithDefaults instantiates a new V1UpdateChannelRequestEmailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UpdateChannelRequestEmailsInnerWithDefaults() *V1UpdateChannelRequestEmailsInner {
	this := V1UpdateChannelRequestEmailsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1UpdateChannelRequestEmailsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateChannelRequestEmailsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1UpdateChannelRequestEmailsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V1UpdateChannelRequestEmailsInner) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value
func (o *V1UpdateChannelRequestEmailsInner) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *V1UpdateChannelRequestEmailsInner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *V1UpdateChannelRequestEmailsInner) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1UpdateChannelRequestEmailsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateChannelRequestEmailsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1UpdateChannelRequestEmailsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1UpdateChannelRequestEmailsInner) SetName(v string) {
	o.Name = &v
}

func (o V1UpdateChannelRequestEmailsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UpdateChannelRequestEmailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["email"] = o.Email
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1UpdateChannelRequestEmailsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1UpdateChannelRequestEmailsInner := _V1UpdateChannelRequestEmailsInner{}

	err = json.Unmarshal(data, &varV1UpdateChannelRequestEmailsInner)

	if err != nil {
		return err
	}

	*o = V1UpdateChannelRequestEmailsInner(varV1UpdateChannelRequestEmailsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "email")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1UpdateChannelRequestEmailsInner struct {
	value *V1UpdateChannelRequestEmailsInner
	isSet bool
}

func (v NullableV1UpdateChannelRequestEmailsInner) Get() *V1UpdateChannelRequestEmailsInner {
	return v.value
}

func (v *NullableV1UpdateChannelRequestEmailsInner) Set(val *V1UpdateChannelRequestEmailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UpdateChannelRequestEmailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UpdateChannelRequestEmailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UpdateChannelRequestEmailsInner(val *V1UpdateChannelRequestEmailsInner) *NullableV1UpdateChannelRequestEmailsInner {
	return &NullableV1UpdateChannelRequestEmailsInner{value: val, isSet: true}
}

func (v NullableV1UpdateChannelRequestEmailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UpdateChannelRequestEmailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
