/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } } 

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the V1CreateChannelRequestSmssInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CreateChannelRequestSmssInner{}

// V1CreateChannelRequestSmssInner struct for V1CreateChannelRequestSmssInner
type V1CreateChannelRequestSmssInner struct {
	Name string `json:"name"`
	Phone string `json:"phone"`
	AdditionalProperties map[string]interface{}
}

type _V1CreateChannelRequestSmssInner V1CreateChannelRequestSmssInner

// NewV1CreateChannelRequestSmssInner instantiates a new V1CreateChannelRequestSmssInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CreateChannelRequestSmssInner(name string, phone string) *V1CreateChannelRequestSmssInner {
	this := V1CreateChannelRequestSmssInner{}
	this.Name = name
	this.Phone = phone
	return &this
}

// NewV1CreateChannelRequestSmssInnerWithDefaults instantiates a new V1CreateChannelRequestSmssInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CreateChannelRequestSmssInnerWithDefaults() *V1CreateChannelRequestSmssInner {
	this := V1CreateChannelRequestSmssInner{}
	return &this
}

// GetName returns the Name field value
func (o *V1CreateChannelRequestSmssInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1CreateChannelRequestSmssInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1CreateChannelRequestSmssInner) SetName(v string) {
	o.Name = v
}

// GetPhone returns the Phone field value
func (o *V1CreateChannelRequestSmssInner) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *V1CreateChannelRequestSmssInner) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *V1CreateChannelRequestSmssInner) SetPhone(v string) {
	o.Phone = v
}

func (o V1CreateChannelRequestSmssInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CreateChannelRequestSmssInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["phone"] = o.Phone

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1CreateChannelRequestSmssInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CreateChannelRequestSmssInner := _V1CreateChannelRequestSmssInner{}

	err = json.Unmarshal(data, &varV1CreateChannelRequestSmssInner)

	if err != nil {
		return err
	}

	*o = V1CreateChannelRequestSmssInner(varV1CreateChannelRequestSmssInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "phone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1CreateChannelRequestSmssInner struct {
	value *V1CreateChannelRequestSmssInner
	isSet bool
}

func (v NullableV1CreateChannelRequestSmssInner) Get() *V1CreateChannelRequestSmssInner {
	return v.value
}

func (v *NullableV1CreateChannelRequestSmssInner) Set(val *V1CreateChannelRequestSmssInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CreateChannelRequestSmssInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CreateChannelRequestSmssInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CreateChannelRequestSmssInner(val *V1CreateChannelRequestSmssInner) *NullableV1CreateChannelRequestSmssInner {
	return &NullableV1CreateChannelRequestSmssInner{value: val, isSet: true}
}

func (v NullableV1CreateChannelRequestSmssInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CreateChannelRequestSmssInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


