/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } } 

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the ChannelWebhookModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelWebhookModel{}

// ChannelWebhookModel struct for ChannelWebhookModel
type ChannelWebhookModel struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Url string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _ChannelWebhookModel ChannelWebhookModel

// NewChannelWebhookModel instantiates a new ChannelWebhookModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelWebhookModel(id string, name string, url string) *ChannelWebhookModel {
	this := ChannelWebhookModel{}
	this.Id = id
	this.Name = name
	this.Url = url
	return &this
}

// NewChannelWebhookModelWithDefaults instantiates a new ChannelWebhookModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelWebhookModelWithDefaults() *ChannelWebhookModel {
	this := ChannelWebhookModel{}
	return &this
}

// GetId returns the Id field value
func (o *ChannelWebhookModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelWebhookModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelWebhookModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ChannelWebhookModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ChannelWebhookModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ChannelWebhookModel) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *ChannelWebhookModel) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ChannelWebhookModel) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ChannelWebhookModel) SetUrl(v string) {
	o.Url = v
}

func (o ChannelWebhookModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelWebhookModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChannelWebhookModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelWebhookModel := _ChannelWebhookModel{}

	err = json.Unmarshal(data, &varChannelWebhookModel)

	if err != nil {
		return err
	}

	*o = ChannelWebhookModel(varChannelWebhookModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChannelWebhookModel struct {
	value *ChannelWebhookModel
	isSet bool
}

func (v NullableChannelWebhookModel) Get() *ChannelWebhookModel {
	return v.value
}

func (v *NullableChannelWebhookModel) Set(val *ChannelWebhookModel) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelWebhookModel) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelWebhookModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelWebhookModel(val *ChannelWebhookModel) *NullableChannelWebhookModel {
	return &NullableChannelWebhookModel{value: val, isSet: true}
}

func (v NullableChannelWebhookModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelWebhookModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


