/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
)

// checks if the V1UpdateProbeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UpdateProbeRequest{}

// V1UpdateProbeRequest struct for V1UpdateProbeRequest
type V1UpdateProbeRequest struct {
	Name *string `json:"name,omitempty"`
	// Only pull probes can have updated URL
	Url                  *string            `json:"url,omitempty"`
	Schedule             ProbeScheduleModel `json:"schedule,omitempty"`
	Channels             []string           `json:"channels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1UpdateProbeRequest V1UpdateProbeRequest

// NewV1UpdateProbeRequest instantiates a new V1UpdateProbeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UpdateProbeRequest() *V1UpdateProbeRequest {
	this := V1UpdateProbeRequest{}
	return &this
}

// NewV1UpdateProbeRequestWithDefaults instantiates a new V1UpdateProbeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UpdateProbeRequestWithDefaults() *V1UpdateProbeRequest {
	this := V1UpdateProbeRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1UpdateProbeRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateProbeRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1UpdateProbeRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1UpdateProbeRequest) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *V1UpdateProbeRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateProbeRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *V1UpdateProbeRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *V1UpdateProbeRequest) SetUrl(v string) {
	o.Url = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *V1UpdateProbeRequest) GetSchedule() ProbeScheduleModel {
	if o == nil || IsNil(o.Schedule) {
		var ret ProbeScheduleModel
		return ret
	}
	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateProbeRequest) GetScheduleOk() (ProbeScheduleModel, bool) {
	if o == nil || IsNil(o.Schedule) {
		return ProbeScheduleModel{}, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *V1UpdateProbeRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given ProbeScheduleModel and assigns it to the Schedule field.
func (o *V1UpdateProbeRequest) SetSchedule(v ProbeScheduleModel) {
	o.Schedule = v
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *V1UpdateProbeRequest) GetChannels() []string {
	if o == nil || IsNil(o.Channels) {
		var ret []string
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UpdateProbeRequest) GetChannelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *V1UpdateProbeRequest) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []string and assigns it to the Channels field.
func (o *V1UpdateProbeRequest) SetChannels(v []string) {
	o.Channels = v
}

func (o V1UpdateProbeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UpdateProbeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1UpdateProbeRequest) UnmarshalJSON(data []byte) (err error) {
	varV1UpdateProbeRequest := _V1UpdateProbeRequest{}

	err = json.Unmarshal(data, &varV1UpdateProbeRequest)

	if err != nil {
		return err
	}

	*o = V1UpdateProbeRequest(varV1UpdateProbeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		delete(additionalProperties, "schedule")
		delete(additionalProperties, "channels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1UpdateProbeRequest struct {
	value *V1UpdateProbeRequest
	isSet bool
}

func (v NullableV1UpdateProbeRequest) Get() *V1UpdateProbeRequest {
	return v.value
}

func (v *NullableV1UpdateProbeRequest) Set(val *V1UpdateProbeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UpdateProbeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UpdateProbeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UpdateProbeRequest(val *V1UpdateProbeRequest) *NullableV1UpdateProbeRequest {
	return &NullableV1UpdateProbeRequest{value: val, isSet: true}
}

func (v NullableV1UpdateProbeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UpdateProbeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
