/*
ObsLabs API

# Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } }

API version: 1.0
Contact: contact@obslabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_go

import (
	"encoding/json"
	"fmt"
)

// checks if the IntegrationModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationModel{}

// IntegrationModel struct for IntegrationModel
type IntegrationModel struct {
	Id                   string                 `json:"id"`
	Type                 string                 `json:"type"`
	Slack                *IntegrationSlackModel `json:"slack,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IntegrationModel IntegrationModel

// NewIntegrationModel instantiates a new IntegrationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationModel(id string, type_ string) *IntegrationModel {
	this := IntegrationModel{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewIntegrationModelWithDefaults instantiates a new IntegrationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationModelWithDefaults() *IntegrationModel {
	this := IntegrationModel{}
	return &this
}

// GetId returns the Id field value
func (o *IntegrationModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IntegrationModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IntegrationModel) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *IntegrationModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *IntegrationModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IntegrationModel) SetType(v string) {
	o.Type = v
}

// GetSlack returns the Slack field value if set, zero value otherwise.
func (o *IntegrationModel) GetSlack() IntegrationSlackModel {
	if o == nil || IsNil(o.Slack) {
		var ret IntegrationSlackModel
		return ret
	}
	return *o.Slack
}

// GetSlackOk returns a tuple with the Slack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationModel) GetSlackOk() (*IntegrationSlackModel, bool) {
	if o == nil || IsNil(o.Slack) {
		return nil, false
	}
	return o.Slack, true
}

// HasSlack returns a boolean if a field has been set.
func (o *IntegrationModel) HasSlack() bool {
	if o != nil && !IsNil(o.Slack) {
		return true
	}

	return false
}

// SetSlack gets a reference to the given IntegrationSlackModel and assigns it to the Slack field.
func (o *IntegrationModel) SetSlack(v IntegrationSlackModel) {
	o.Slack = &v
}

func (o IntegrationModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	if !IsNil(o.Slack) {
		toSerialize["slack"] = o.Slack
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IntegrationModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationModel := _IntegrationModel{}

	err = json.Unmarshal(data, &varIntegrationModel)

	if err != nil {
		return err
	}

	*o = IntegrationModel(varIntegrationModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "slack")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIntegrationModel struct {
	value *IntegrationModel
	isSet bool
}

func (v NullableIntegrationModel) Get() *IntegrationModel {
	return v.value
}

func (v *NullableIntegrationModel) Set(val *IntegrationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationModel(val *IntegrationModel) *NullableIntegrationModel {
	return &NullableIntegrationModel{value: val, isSet: true}
}

func (v NullableIntegrationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
